# Generated by Django 4.1.7 on 2023-02-27 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0002_molel2_alter_molel1_options_molel1_pole3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='molel2',
            name='pole3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site1.molel1'),
        ),
    ]
