# Generated by Django 4.1.7 on 2023-02-27 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0003_alter_molel2_pole3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='molel2',
            name='pole3',
        ),
    ]
