# Generated by Django 4.1.7 on 2023-02-27 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0005_molel2_pole3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='molel2',
            name='pole3',
        ),
        migrations.AddField(
            model_name='molel2',
            name='pole4',
            field=models.ManyToManyField(to='site1.molel1'),
        ),
    ]
