# Generated by Django 4.1.7 on 2023-03-10 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0006_remove_molel2_pole3_molel2_pole4'),
    ]

    operations = [
        migrations.CreateModel(
            name='Molel3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pole1', models.CharField(max_length=45)),
                ('pole2', models.TextField()),
            ],
            options={
                'verbose_name': 'Модель',
                'verbose_name_plural': 'Модели',
            },
        ),
    ]
