# Generated by Django 4.1.7 on 2023-03-11 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0008_molel4_alter_molel3_pole1_alter_molel3_pole2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Molel5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pole1', models.CharField(max_length=45, verbose_name='Наши контакты')),
                ('pole2', models.TextField(verbose_name='Наши контакты')),
            ],
            options={
                'verbose_name': 'Модель',
                'verbose_name_plural': 'Модели',
            },
        ),
        migrations.AlterField(
            model_name='molel3',
            name='pole1',
            field=models.CharField(max_length=45, verbose_name='Название статьи'),
        ),
        migrations.AlterField(
            model_name='molel3',
            name='pole2',
            field=models.TextField(verbose_name='Текст статьи'),
        ),
    ]
